\[package]
name = "pussy"
version = "0.1.0"
edition = "2021"
description = "PUSSY — Portable Uncensorable Storage SYstem on Nostr"
authors = \["Your Name [you@example.com](mailto:you@example.com)"]
license = "MIT"

\[dependencies]

# Nostr SDK for publishing/fetching events

nostr-sdk = "0.26"

# Crypto

aes-gcm = "0.10"        # AES-256-GCM encryption
aes = "0.8"
rand = "0.8"
scrypt = "0.10"
sha2 = "0.10"
hex = "0.4"
base64 = "0.21"

# CLI args

clap = { version = "4.4", features = \["derive"] }

# Async runtime

tokio = { version = "1.37", features = \["full"] }

# Config + serde

serde = { version = "1.0", features = \["derive"] }
serde\_json = "1.0"
dirs = "5.0"
